// ════════════════════════════════════════════════════════════
// build-seo.mjs — génère les pages statiques indexables
// ════════════════════════════════════════════════════════════
//
// GitHub Pages ne sert que des fichiers : sans ce script, chaque
// article n'existe que via /?article=ID (canonical = accueil) et
// chaque profil renvoie un code 404. Ce script crée :
//   • /article/<id>-<slug>/index.html  (une vraie page par article)
//   • /<profil>/index.html             (une vraie page par auteur)
//   • /sitemap.xml                     (toutes ces URL)
// Chaque page est une copie de index.html avec ses propres balises
// <title>, description, canonical, Open Graph et JSON-LD, plus le
// contenu de l'article pré-rendu pour les robots.
//
// Usage : node scripts/build-seo.mjs
// Lancé automatiquement par .github/workflows/seo.yml

import { readFile, writeFile, mkdir, rm, readdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SITE = 'https://www.econglobe.com';
const SUPABASE_URL = process.env.SUPABASE_URL || 'https://soimafxvczlxdqvybkut.supabase.co';
const SUPABASE_KEY = process.env.SUPABASE_KEY || 'sb_publishable_iAixQG010qsVC_c-1S6RTA_yIiXrLIB';
const MARKER = '<!-- generated by scripts/build-seo.mjs -->';
const DEFAULT_IMAGE = `${SITE}/css/Logo.png`;
// Dossiers du dépôt qu'un profil ne doit jamais écraser
const RESERVED = new Set(['article', 'css', 'js', 'supabase', 'scripts', 'privacy', 'terms', 'index', '404']);
const MONTHS = { janvier: 1, fevrier: 2, mars: 3, avril: 4, mai: 5, juin: 6, juillet: 7, aout: 8, septembre: 9, octobre: 10, novembre: 11, decembre: 12 };

// ── Mêmes règles que js/data.js (articleSlug / articlePath) et js/articles.js (profileSlug)
const stripAccents = s => String(s || '').normalize('NFD').replace(/[\u0300-\u036f]/g, '');
const articleSlug = title => stripAccents(title).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 80).replace(/-+$/, '');
const articlePath = a => { const slug = articleSlug(a.title); return `/article/${a.id}${slug ? '-' + slug : ''}/`; };
const profileSlug = u => stripAccents(`${u.first || ''}${u.last || ''}`).toLowerCase().replace(/[^a-z0-9]/g, '');

const esc = s => String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const plain = html => String(html || '').replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').trim();
const truncate = (s, n) => s.length > n ? s.slice(0, n - 1).replace(/\s+\S*$/, '') + '…' : s;

function isoDate(frDate) {
  const m = stripAccents(frDate).toLowerCase().match(/(\d{1,2})(?:er)?\s+([a-z]+)\s+(\d{4})/);
  if (!m || !MONTHS[m[2]]) return null;
  return `${m[3]}-${String(MONTHS[m[2]]).padStart(2, '0')}-${m[1].padStart(2, '0')}`;
}

async function query(table, params) {
  const res = await fetch(`${SUPABASE_URL}/rest/v1/${table}?${params}`, {
    headers: { apikey: SUPABASE_KEY, Authorization: `Bearer ${SUPABASE_KEY}` }
  });
  if (!res.ok) throw new Error(`${table}: HTTP ${res.status} ${await res.text()}`);
  return res.json();
}

// Corps de l'article sans images base64 (trop lourdes pour le HTML statique) ni scripts
function articleBody(a) {
  const html = a.body_html || String(a.body || '').split(/\n\n+/).map(p => `<p>${esc(p).replace(/\n/g, '<br>')}</p>`).join('');
  return html
    .replace(/<script[\s\S]*?<\/script>/gi, '')
    .replace(/<img[^>]+src=["']data:[^>]*>/gi, '');
}

// Image de couverture : URL distante telle quelle, data URI → fichier cover.<ext>
async function coverImage(a, dir) {
  if (!a.img) return null;
  const m = String(a.img).match(/^data:image\/(png|jpe?g|webp|gif);base64,(.+)$/);
  if (!m) return /^https?:\/\//.test(a.img) ? a.img : null;
  const ext = m[1] === 'jpeg' ? 'jpg' : m[1];
  await writeFile(path.join(dir, `cover.${ext}`), Buffer.from(m[2], 'base64'));
  return `${SITE}${articlePath(a)}cover.${ext}`;
}

function buildPage(template, { lang, title, description, url, image, type, jsonLd, noscript, articleHtml }) {
  const fullTitle = `${title} | EconGlobe`;
  const set = (html, re, value) => {
    if (!re.test(html)) throw new Error(`index.html : balise introuvable ${re}`);
    return html.replace(re, value);
  };
  let html = template;
  html = set(html, /<html lang="[^"]*"/, `<html lang="${lang}"`);
  html = set(html, /<head>/, `<head>\n${MARKER}\n<base href="/">`);
  html = set(html, /<title>[^<]*<\/title>/, `<title>${esc(fullTitle)}</title>`);
  html = set(html, /<meta name="description" content="[^"]*">/, `<meta name="description" content="${esc(description)}">`);
  html = set(html, /<link rel="canonical" href="[^"]*">/, `<link rel="canonical" href="${url}">`);
  html = set(html, /<meta property="og:locale" content="[^"]*">/, `<meta property="og:locale" content="${lang === 'en' ? 'en_US' : 'fr_FR'}">`);
  html = set(html, /<meta property="og:locale:alternate" content="[^"]*">/, `<meta property="og:locale:alternate" content="${lang === 'en' ? 'fr_FR' : 'en_US'}">`);
  html = set(html, /<meta property="og:type" content="[^"]*">/, `<meta property="og:type" content="${type}">`);
  html = set(html, /<meta property="og:title" content="[^"]*">/, `<meta property="og:title" content="${esc(title)}">`);
  html = set(html, /<meta property="og:description" content="[^"]*">/, `<meta property="og:description" content="${esc(description)}">`);
  html = set(html, /<meta property="og:url" content="[^"]*">/, `<meta property="og:url" content="${url}">`);
  html = set(html, /<meta property="og:image" content="[^"]*">/, `<meta property="og:image" content="${esc(image)}">`);
  html = html.replace(/<meta property="og:image:(width|height|type)" content="[^"]*">\n?/g, '');
  html = set(html, /<meta property="og:image:alt" content="[^"]*">/, `<meta property="og:image:alt" content="${esc(title)}">`);
  html = set(html, /<meta name="twitter:card" content="[^"]*">/, `<meta name="twitter:card" content="${image === DEFAULT_IMAGE ? 'summary' : 'summary_large_image'}">`);
  html = set(html, /<meta name="twitter:title" content="[^"]*">/, `<meta name="twitter:title" content="${esc(title)}">`);
  html = set(html, /<meta name="twitter:description" content="[^"]*">/, `<meta name="twitter:description" content="${esc(description)}">`);
  html = set(html, /<meta name="twitter:image" content="[^"]*">/, `<meta name="twitter:image" content="${esc(image)}">`);
  html = set(html, /<script type="application\/ld\+json">[\s\S]*?<\/script>/, `<script type="application/ld+json">\n${JSON.stringify(jsonLd, null, 2).replace(/</g, '\\u003c')}\n</script>`);
  html = set(html, /<noscript>\s*<main>[\s\S]*?<\/main>\s*<\/noscript>/, `<noscript>\n  <main>\n${noscript}\n  </main>\n</noscript>`);
  if (articleHtml) html = set(html, /<div class="article-page" id="article-content"><\/div>/, `<div class="article-page" id="article-content">${articleHtml}</div>`);
  return html;
}

const organization = { '@type': 'Organization', '@id': `${SITE}/#organization`, name: 'EconGlobe', url: `${SITE}/`, logo: DEFAULT_IMAGE };

async function main() {
  const template = (await readFile(path.join(ROOT, 'index.html'), 'utf8')).replace(/\r\n/g, '\n');
  if (template.includes(MARKER)) throw new Error('index.html est une page générée : modèle invalide');

  const [articles, profiles] = await Promise.all([
    query('articles', 'select=id,owner_id,title,deck,cat,author,img,body,body_html,date,lang&or=(status.eq.published,status.is.null)&order=id'),
    query('profiles', 'select=id,first,last,avatar,bio')
  ]);

  // Nettoyage des pages générées précédemment (articles supprimés, profils renommés…)
  await rm(path.join(ROOT, 'article'), { recursive: true, force: true });
  for (const entry of await readdir(ROOT, { withFileTypes: true })) {
    const file = path.join(ROOT, entry.name, 'index.html');
    if (entry.isDirectory() && existsSync(file) && (await readFile(file, 'utf8')).includes(MARKER)) {
      await rm(path.join(ROOT, entry.name), { recursive: true, force: true });
    }
  }

  const sitemap = [{ loc: `${SITE}/`, priority: '1.0', changefreq: 'daily' }];
  const authorOf = a => profiles.find(p => a.owner_id && String(p.id) === String(a.owner_id))
    || profiles.find(p => `${p.first || ''} ${p.last || ''}`.trim().toLowerCase() === String(a.author || '').trim().toLowerCase());

  for (const a of articles) {
    const urlPath = articlePath(a);
    const dir = path.join(ROOT, urlPath);
    await mkdir(dir, { recursive: true });
    const url = `${SITE}${urlPath}`;
    const lang = a.lang === 'en' ? 'en' : 'fr';
    const description = truncate(a.deck || plain(articleBody(a)), 160);
    const image = (await coverImage(a, dir)) || DEFAULT_IMAGE;
    const published = isoDate(a.date);
    const author = authorOf(a);
    const authorUrl = author && !RESERVED.has(profileSlug(author)) ? `${SITE}/${profileSlug(author)}/` : undefined;
    const body = articleBody(a);
    const header = `<div class="art-full-k">${esc(a.cat)}</div>
    <h1 class="art-full-title">${esc(a.title)}</h1>
    <div class="art-full-deck">${esc(a.deck)}</div>
    <div class="art-full-meta"><span>${authorUrl ? `<a class="author-chip" href="${authorUrl}">${esc(a.author)}</a>` : esc(a.author)}</span><span class="dot"></span><span>${esc(a.date)}</span></div>`;
    const html = buildPage(template, {
      lang, title: a.title, description, url, image, type: 'article',
      jsonLd: {
        '@context': 'https://schema.org',
        '@graph': [organization, {
          '@type': 'Article',
          headline: truncate(a.title, 110),
          description,
          image: [image],
          ...(published && { datePublished: published, dateModified: published }),
          author: { '@type': 'Person', name: a.author, ...(authorUrl && { url: authorUrl }) },
          publisher: { '@id': `${SITE}/#organization` },
          mainEntityOfPage: url,
          articleSection: a.cat,
          inLanguage: lang
        }]
      },
      noscript: `    <article>${header}\n    <div class="art-full-body">${body}</div></article>`,
      articleHtml: `\n    ${header}\n    <div class="art-full-body">${body}</div>\n  `
    });
    await writeFile(path.join(dir, 'index.html'), html);
    sitemap.push({ loc: url, lastmod: published, priority: '0.8', changefreq: 'monthly' });
  }

  for (const p of profiles) {
    const slug = profileSlug(p);
    if (!slug || RESERVED.has(slug)) continue;
    const dir = path.join(ROOT, slug);
    if (existsSync(dir)) { console.warn(`Profil ignoré, le dossier /${slug}/ existe déjà`); continue; }
    const name = `${p.first || ''} ${p.last || ''}`.replace(/\s+\.$/, '').trim();
    const own = articles.filter(a => authorOf(a) === p).reverse();
    const url = `${SITE}/${slug}/`;
    const description = truncate(plain(p.bio) || `Profil de ${name} sur EconGlobe.`, 160);
    const image = p.avatar && /^https?:\/\//.test(p.avatar) ? p.avatar : DEFAULT_IMAGE;
    const list = own.map(a => `<li><a href="${articlePath(a)}">${esc(a.title)}</a></li>`).join('');
    const html = buildPage(template, {
      lang: 'fr', title: name, description, url, image, type: 'profile',
      jsonLd: {
        '@context': 'https://schema.org',
        '@graph': [organization, {
          '@type': 'ProfilePage',
          url,
          mainEntity: { '@type': 'Person', name, ...(p.bio && { description: plain(p.bio) }), ...(image !== DEFAULT_IMAGE && { image }) }
        }]
      },
      noscript: `    <h1>${esc(name)}</h1>\n    ${p.bio ? `<p>${esc(plain(p.bio))}</p>` : ''}\n    ${list ? `<ul>${list}</ul>` : ''}`
    });
    // Les profils sans article publié restent accessibles (code 200) mais hors index
    await mkdir(dir, { recursive: true });
    await writeFile(path.join(dir, 'index.html'), own.length ? html : html.replace(/<meta name="robots" content="[^"]*">/, '<meta name="robots" content="noindex, follow">'));
    if (own.length) sitemap.push({ loc: url, priority: '0.6', changefreq: 'weekly' });
  }

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${sitemap.map(u => `  <url>
    <loc>${esc(u.loc)}</loc>${u.lastmod ? `\n    <lastmod>${u.lastmod}</lastmod>` : ''}
    <changefreq>${u.changefreq}</changefreq>
    <priority>${u.priority}</priority>
  </url>`).join('\n')}
</urlset>
`;
  await writeFile(path.join(ROOT, 'sitemap.xml'), xml);
  console.log(`${articles.length} article(s), ${sitemap.length} URL dans le sitemap`);
}

main().catch(err => { console.error(err); process.exit(1); });
